-- 依存関係のあるテーブルから順に削除
DROP TABLE IF EXISTS item_tags CASCADE;
DROP TABLE IF EXISTS tag_values CASCADE;
DROP TABLE IF EXISTS tag_categories CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS input_items CASCADE;
DROP TABLE IF EXISTS input_groups CASCADE;
